---
- name: Configura firewall utilizzando il parser
  hosts: target_host
  become: true  # Esegue i comandi con privilegi di root
  tasks:

    - name: Verifica se lo script firewall_parser.sh esiste
      stat:
        path: /usr/local/bin/firewall_parser.sh
      register: firewall_script_stat

    - name: Copia il parser se non esiste
      copy:
        src: /path/to/local/firewall_parser.sh  # Percorso dello script nel sistema locale
        dest: /usr/local/bin/firewall_parser.sh
        mode: '0755'
      when: not firewall_script_stat.stat.exists

    - name: Esegui il parser per inserire una regola firewall
      command: >
        /usr/local/bin/firewall_parser.sh {{ chain }} {{ srcaddr }} {{ protocol }} {{ sport }} {{ dstaddr }} {{ dport }} {{ action }}
      args:
        chdir: /usr/local/bin
