---
- name: Configura firewall utilizzando il parser
  hosts: firewallo
  become: true  # Esegue i comandi con privilegi di root
  tasks:

    - name: Verifica se lo script firewall_parser.sh esiste
      stat:
        path: /usr/local/firewallo/ansible/filter_parser.sh
      register: firewall_script_stat

    - name: Esegui il parser per inserire una regola firewall
      command: >
        /usr/local/firewallo/ansible/filter_parser.sh {{ chain }} {{ srcaddr }} {{ protocol }} {{ sport }} {{ dstaddr }} {{ dport }} {{ action }} {{ comment }}
      args:
        chdir: /usr/local/bin
