---
- hosts: firewallo
  become: yes
  tasks:
    - name: Check if Git is installed
      apt:
        name: git
        state: present
      become: yes

    - name: Check if iptables is installed
      apt:
        name: iptables
        state: present
      become: yes

    - name: Check if nftables is installed
      apt:
        name: nftables
        state: present
      become: yes
    
    - name: check if directory /opt/firewallo exist
      file:
        path: /opt/firewallo
        state: directory
        mode: '0755'
        owner: root
        group: root
    
    - name: Enable sparse checkout
      command: git config core.sparseCheckout true
      args:
        chdir: /opt/firewallo

    - name: Set sparse checkout patterns (exclude README and LICENSE)
      copy:
        content: |
          /*                   # Clone
          !/README             # Exclude README
          !/LICENSE            # Exclude LICENSE
        dest: /opt/firewallo/.git/info/sparse-checkout
        
    - name: Clone repository firewallo in /opt/firewallo
      git:
        repo: 'https://github.com/un1x80/firewallo.git'
        dest: /opt/firewallo
        version: main
      register: result_git
    
    - name: Ensure dpkg-dev is installed
      apt:
        name: dpkg-dev
        state: present
        update_cache: yes
      become: yes

    - name: Build the .deb package
      command: dpkg-deb --build /opt/firewallo
      args:
        chdir: /opt/
    
    - name: Ensure the package was created
      stat:
        path: /opt/firewallo.deb
      register: package_stat

    - name: Fail if package was not created
      fail:
        msg: "The .deb package was not created!"
      when: not package_stat.stat.exists

    - name: Notify user that package was created
      debug:
        msg: "The .deb package has been successfully built: /opt/firewallo.deb"

    - name: Install the .deb package
      apt:
        deb: /opt/firewallo.deb